name: Run auto tests with Pytest and Pylenium

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          pip install poetry
          # install dependencies from pyproject.toml
          poetry install

      - name: Run E2E Tests
        run: |
          poetry run pytest tests/test_todo.py -n 2
